// pages/index.vue
<template>
  <div>
    <div class="flex flex-col min-h-screen bg-gray-200 dark:bg-gray-800">
      <Header @showShareModal="showShareModal" />
      <Links @showShareModal="showShareModal" />
      <Footer />
      <ShareModal :show="showModal" @hideShareModal="hideShareModal" :url="url" />
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'IndexPage',
  data(){
    return {
      showModal: false,
      url: ''
    }
  },
  methods: {
    showShareModal (url = '') {
      this.showModal = true
      this.url = url
    },
    hideShareModal(){
      this.showModal = false
    }
  }
})
</script>

// pages/index.tsx
import Head from 'next/head'
import Header from "../components/Header";
import Footer from "../components/Footer";
import Links from "../components/Links";

export default function Home() {
    return (
        <div className="flex flex-col min-h-screen bg-gray-200 dark:bg-gray-800">
            <Head>
                <title>Muhammad Daimus Suudi</title>
                <meta name="description" content="Daimus short link"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header/>
            <Links/>
            <Footer/>
        </div>
    )
}
